In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

waiting_time_df = pd.read_csv('waiting_time_data.csv', index_col = 0)

reference_dict = {
    "North_a" : "785902529",
    "North_f" : "-785902529",
    "West_a" : "785902540#0",
    "West_f" : "-785902540#1",
    "South_a" : "-732022517",
    "South_f" : "732022517",
    "East_a" : "-785902540#2",
    "East_f" : "785902540#2"}
reference_dict_reverse = dict((v,k) for k,v in reference_dict.items())

reference_dict_reverse_w_lanes = []
for key in reference_dict_reverse.keys():
    reference_dict_reverse_w_lanes.append(key+'_0')
    reference_dict_reverse_w_lanes.append(key+'_1')

waiting_time_df = waiting_time_df[reference_dict_reverse_w_lanes]
new_column_name = []
for key in waiting_time_df.keys():
    lane, lane_no = key.split('_')

    new_column_name.append(reference_dict_reverse[lane]+'_'+lane_no)


for index, column_name in enumerate(new_column_name):
    waiting_time_df = waiting_time_df.rename(columns={waiting_time_df.keys()[index]:column_name})

waiting_time_df

,North_a_0,North_a_1,North_f_0,North_f_1,West_a_0,West_a_1,West_f_0,West_f_1,South_a_0,South_a_1,South_f_0,South_f_1,East_a_0,East_a_1,East_f_0,East_f_1
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28791,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28792,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28793,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28794,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28795,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [62]:
df_dict={}
for key in waiting_time_df.keys():
    df_dict[key]=waiting_time_df[[key]].loc[waiting_time_df[key]>0]

North_a_0
North_a_1
North_f_0
North_f_1
West_a_0
West_a_1
West_f_0
West_f_1
South_a_0
South_a_1
South_f_0
South_f_1
East_a_0
East_a_1
East_f_0
East_f_1